name: motif
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11.8
  - pip=24.2
  - appnope=0.1.4
  - asttokens=2.4.1
  - bzip2=1.0.8
  - comm=0.2.2
  - debugpy=1.8.9
  - decorator=5.1.1
  - exceptiongroup=1.2.2
  - executing=2.1.0
  - importlib-metadata=8.5.0
  - ipykernel=6.29.5
  - ipython=8.29.0
  - jedi=0.19.2
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - matplotlib-inline=0.1.7
  - nest-asyncio=1.6.0
  - packaging=24.2
  - parso=0.8.4
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - platformdirs=4.3.6
  - prompt-toolkit=3.0.48
  - psutil=6.1.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pygments=2.18.0
  - python-dateutil=2.9.0
  - pyzmq=26.2.0
  - setuptools=75.1.0
  - six=1.16.0
  - stack_data=0.6.2
  - tornado=6.4.2
  - traitlets=5.14.3
  - typing_extensions=4.12.2
  - wcwidth=0.2.13
  - wheel=0.44.0
  - pip:
    - anyio==4.8.0
    - attrs==24.3.0
    - baycomp==1.0.3
    - biothings-client==0.4.1
    - cattrs==24.1.2
    - certifi==2024.12.14
    - charset-normalizer==3.4.1
    - click==8.1.7
    - cloudpickle==3.1.0
    - contourpy==1.3.1
    - cycler==0.12.1
    - dask==2024.11.2
    - distributed==2024.11.2
    - fonttools==4.56.0
    - fsspec==2024.10.0
    - h11==0.14.0
    - httpcore==1.0.7
    - httpx==0.28.1
    - idna==3.10
    - jinja2==3.1.4
    - joblib==1.4.2
    - kiwisolver==1.4.8
    - levenshtein==0.26.1
    - locket==1.0.0
    - markupsafe==3.0.2
    - matplotlib==3.10.0
    - msgpack==1.1.0
    - mygene==3.2.2
    - networkx==3.4.2
    - numpy==2.1.3
    - pandas==2.2.3
    - partd==1.4.2
    - pillow==11.1.0
    - pybiomart==0.2.0
    - pyparsing==3.2.1
    - python-levenshtein==0.26.1
    - pytz==2024.2
    - pyyaml==6.0.2
    - ranky==0.3.5
    - rapidfuzz==3.12.1
    - requests==2.32.3
    - requests-cache==1.2.1
    - scikit-learn==1.5.2
    - scipy==1.14.1
    - seaborn==0.13.2
    - sniffio==1.3.1
    - sortedcontainers==2.4.0
    - tblib==3.0.0
    - threadpoolctl==3.5.0
    - toolz==1.0.0
    - tqdm==4.67.1
    - tzdata==2024.2
    - url-normalize==1.4.3
    - urllib3==2.2.3
    - zict==3.0.0